[mongodb]
mongodb.dpspk142034.fun

[redis]
redis.dpspk142034.fun

[mysql]
mysql.dpspk142034.fun

[rabbitmq]
rabbitmq.dpspk142034.fun

[frontend]
172.31.18.243

[cart]
172.31.18.243

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
NAME=from inventory
; COURSE=Ansible
; DURATION=10HRS
; TRAINER=Sivakumar